#!/bin/bash
#This is the shell script to run shadowsocksR in the background.

curPath=$(cd `dirname $0`; pwd)
eval $(ps -ef | grep -v grep | grep local.py | awk '{ print "kill -9 " $2 }')
nohup python $curPath/shadowsocks/local.py -c $curPath/config/config.json >> $curPath/shadowsocks/ssserver.log 2>&1 &
